#NoEnv  ; Recommended for performance and compatibility with future AutoHotkey releases.
; #Warn  ; Enable warnings to assist with detecting common errors.
SendMode Input  ; Recommended for new scripts due to its superior speed and reliability.
SetWorkingDir %A_ScriptDir%  ; Ensures a consistent starting directory.



openURL(u) {
	WinActivate, Program Manager
	Run %u%
	return
}


^1::
OpenURL("https://server.pro/11391390")
CoordMode, Mouse, Screen
sleep, 2000
Click, 2073, 966
sleep, 1000
Click, 2716, 607
WinActivate, ahk_exe Discord.exe
sleep, 1000
Click, 1956, 163
Click, 2108, 223
Send, *renewed* (generated by Ryan's script)